CREATE TABLE IF NOT EXISTS Part (
    ID INTEGER PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES Asset(ID)
        ON UPDATE NO ACTION ON DELETE CASCADE,
    Type_ID INTEGER NOT NULL,
    FOREIGN KEY (Type_ID) REFERENCES Part_Type(ID)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    Description VARCHAR(500) NOT NULL,
    Was_Purchased BOOLEAN NOT NULL,
    Contained_In INTEGER NULL,
    FOREIGN KEY (Contained_In) REFERENCES Device(ID)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);