create table Device (
    ID INTEGER PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES Asset(ID),
    Manufacturer_ID INTEGER NOT NULL,
    FOREIGN KEY (Manufacturer_ID) REFERENCES Manufacturer(ID),
    Model VARCHAR(50) NOT NULL,
    Year INTEGER NULL,
    CHECK (Year >= 1980 AND Year <= EXTRACT(YEAR FROM CURRENT_DATE)),
    CPU VARCHAR(50) NULL,
    RAM INTEGER DEFAULT 0 NOT NULL,
    CHECK (RAM >= 0),
    RAM_Generation_ID INTEGER NULL,
    FOREIGN KEY (RAM_Generation_ID) REFERENCES Ram_Generation(ID),
    Storage_Amount INTEGER DEFAULT 0 NOT NULL,
    CHECK (Storage_Amount >= 0),
    Storage_Type_ID INTEGER NULL,
    FOREIGN KEY (Storage_Type_ID) REFERENCES Storage_Type(ID),
    Status Status NOT NULL,
    Recipient_ID INTEGER NULL,
    FOREIGN KEY (Recipient_ID) REFERENCES Party(ID)
);