create table Note (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Text VARCHAR(500) NOT NULL,
    Date TIMESTAMP WITH TIME ZONE NOT NULL,
    Asset_ID INTEGER NOT NULL,
    FOREIGN KEY (Asset_ID) REFERENCES Asset(ID)
);