CREATE TABLE IF NOT EXISTS Tool (
    ID INTEGER NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES Asset(ID),
    Type_ID INTEGER NOT NULL,
    FOREIGN KEY (Type_ID) REFERENCES Tool_Type(ID),
    Description varchar(500) NOT NULL
);