CREATE TABLE IF NOT EXISTS Asset_Change_Log (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Device_ID INTEGER NOT NULL,
    Modified_By Name_Type NOT NULL,
    Modified_At TIMESTAMPTZ DEFAULT now(),
    transaction_id BIGINT NOT NULL DEFAULT txid_current(),
    Change_Type Change_Type NOT NULL,
    Old_Manufacturer_ID INTEGER NULL,
    New_Manufacturer_ID INTEGER NULL,
    Old_Model VARCHAR(50) NULL,
    New_Model VARCHAR(50) NULL,
    Old_Year INTEGER NULL,
    New_Year INTEGER NULL,
    Old_CPU VARCHAR(50) NULL,
    New_CPU VARCHAR(50) NULL,
    Old_RAM INTEGER NULL,
    New_RAM INTEGER NULL,
    Old_RAM_Generation_ID INTEGER NULL,
    New_RAM_Generation_ID INTEGER NULL,
    Old_Storage_Amount INTEGER NULL,
    New_Storage_Amount INTEGER NULL,
    Old_Storage_Type_ID INTEGER NULL,
    New_Storage_Type_ID INTEGER NULL,
    Old_Status Status NULL,
    New_Status Status NULL,
    Old_Recipient_ID INTEGER NULL,
    New_Recipient_ID INTEGER NULL,
    Old_Donated_Date DATE NULL,
    New_Donated_Date DATE NULL,
    Old_OS_ID INTEGER NULL,
    New_OS_ID INTEGER NULL
);