CREATE OR REPLACE FUNCTION Update_Tablet_Change_Log()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    
END;
$$;

CREATE OR REPLACE TRIGGER Trg_Update_Tablet_Change_Log
    AFTER INSERT OR UPDATE OR DELETE ON Tablet
    FOR EACH ROW
    EXECUTE FUNCTION Update_Tablet_Change_Log();