/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/accounts": {
    /**
     * List accounts
     * @description Admins see all accounts. Chapter Admins see only accounts in their chapters.
     */
    get: {
      responses: {
        /** @description Account list returned */
        200: {
          content: {
            "application/json": components["schemas"]["AccountSummary"][];
          };
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
    /**
     * Create a new account
     * @description Admins can create Chapter Admin / Editor / Viewer accounts for any chapter. Chapter Admins can create Editor / Viewer accounts for their own chapters.
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateAccountRequest"];
        };
      };
      responses: {
        /** @description Account created */
        201: {
          content: {
            "application/json": components["schemas"]["AccountSummary"];
          };
        };
        /** @description Invalid request or forbidden role */
        400: {
          content: never;
        };
        /** @description Username already taken */
        409: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/accounts/{id}": {
    /**
     * Update account password
     * @description Allows a logged-in user to update their own password.
     */
    put: {
      parameters: {
        path: {
          /** @description The ID of the account whose password to change */
          id: string;
        };
      };
      requestBody: {
        content: {
          /**
           * @example {
           *     "currentPassword": "oldPassword123",
           *     "newPassword": "12345678"
           * }
           */
          "application/json": components["schemas"]["UpdatePasswordRequest"];
        };
      };
      responses: {
        /** @description Password updated */
        204: {
          content: never;
        };
        /** @description Invalid request or wrong current password */
        400: {
          content: never;
        };
        /** @description Cannot change another user's password */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
    /** Delete an account (admin only) */
    delete: {
      parameters: {
        path: {
          /** @description Volunteer ID to delete */
          id: string;
        };
      };
      responses: {
        /** @description Account deleted */
        204: {
          content: never;
        };
        /** @description Cannot delete own account */
        400: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/accounts/{id}/roles": {
    /** Add a chapter/role affiliation to an existing account */
    post: {
      parameters: {
        path: {
          /** @description Volunteer ID */
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddAffiliationRequest"];
        };
      };
      responses: {
        /** @description Affiliation added */
        204: {
          content: never;
        };
        /** @description Invalid role or missing chapter access */
        400: {
          content: never;
        };
        /** @description Affiliation already exists */
        409: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/accounts/{id}/roles/{chapterId}": {
    /** Update the role for a chapter affiliation */
    put: {
      parameters: {
        path: {
          /** @description Volunteer ID */
          id: string;
          /** @description Chapter ID */
          chapterId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateAffiliationRequest"];
        };
      };
      responses: {
        /** @description Role updated */
        204: {
          content: never;
        };
        /** @description Invalid role or missing chapter access */
        400: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
    /** Remove a chapter affiliation from an account */
    delete: {
      parameters: {
        path: {
          /** @description Volunteer ID */
          id: string;
          /** @description Chapter ID to remove */
          chapterId: string;
        };
      };
      responses: {
        /** @description Affiliation removed */
        204: {
          content: never;
        };
        /** @description Validation error */
        400: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/assets/{id}/exists": {
    /**
     * Check if an asset exists
     * @description Returns true if an asset with the given ID exists, false otherwise.
     */
    get: {
      parameters: {
        path: {
          /** @description The unique ID of the asset to check */
          id: string;
        };
      };
      responses: {
        /** @description Check completed successfully */
        200: {
          content: {
            "application/json": boolean;
          };
        };
        /** @description Invalid ID format */
        400: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/assets/{id}/notes": {
    /** Get a list of notes belonging to a given asset */
    get: {
      parameters: {
        path: {
          /** @description The unique ID of the asset whose notes will be retrieved */
          id: string;
        };
      };
      responses: {
        /** @description Notes fetched successfully */
        200: {
          content: {
            "application/json": components["schemas"]["NoteResponse"][];
          };
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
    /** Add a new note to an asset with the given ID */
    post: {
      parameters: {
        path: {
          /** @description The unique ID of the asset to which the new note will be assigned */
          id: string;
        };
      };
      requestBody: {
        content: {
          /**
           * @example {
           *     "text": "New Note"
           * }
           */
          "application/json": components["schemas"]["PostNoteRequest"];
        };
      };
      responses: {
        /** @description Note added successfully */
        201: {
          content: {
            "application/json": components["schemas"]["NoteResponse"];
          };
        };
        /** @description Missing required parameters */
        400: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/assets/{id}/notes/{noteId}": {
    /** Update a note belonging to an asset */
    put: {
      parameters: {
        path: {
          /** @description The unique ID of the asset */
          id: string;
          /** @description The unique ID of the note to update */
          noteId: string;
        };
      };
      requestBody: {
        content: {
          /**
           * @example {
           *     "text": "Updated Note"
           * }
           */
          "application/json": components["schemas"]["PostNoteRequest"];
        };
      };
      responses: {
        /** @description Note updated successfully */
        201: {
          content: never;
        };
        /** @description Missing required parameters */
        400: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/auth/login": {
    /**
     * Login
     * @description Authenticate a volunteer and receive a JWT token
     */
    post: {
      requestBody: {
        content: {
          /**
           * @example {
           *     "username": "user123",
           *     "password": "pass123"
           * }
           */
          "application/json": components["schemas"]["LoginRequest"];
        };
      };
      responses: {
        /** @description Login successful */
        200: {
          content: {
            "application/json": components["schemas"]["LoginResponse"];
          };
        };
        /** @description Missing username or password */
        400: {
          content: never;
        };
        /** @description Invalid credentials */
        401: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/chapters": {
    /** List all chapters */
    get: {
      responses: {
        /** @description Chapter list */
        200: {
          content: {
            "application/json": components["schemas"]["ChapterSummary"][];
          };
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
    /**
     * Create a new chapter
     * @description Creates a new chapter. Restricted to national admins: users with the Admin role who are affiliated with the National chapter.
     */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateChapterRequest"];
        };
      };
      responses: {
        /** @description Chapter created */
        201: {
          content: {
            "application/json": components["schemas"]["ChapterSummary"];
          };
        };
        /** @description Missing or blank chapter name */
        400: {
          content: never;
        };
        /** @description Caller is not affiliated with the National chapter */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices": {
    /**
     * Retrieve a page of devices
     * @description Returns a filtered, sorted, paginated page of devices the user can access. pageSize is required; results are ordered by the requested sort column then id.
     */
    get: {
      parameters: {
        query: {
          /** @description Number of records per page (1-1000). Required. */
          pageSize: number;
          /** @description Zero-based page index. Defaults to 0. */
          pageKey?: number;
          /** @description Free-text search matched against every device field (id, manufacturer, model, cpu, chapter, status, operating system, etc.). */
          search?: string;
          /** @description Filter by device type: Desktop, Laptop or Tablet. */
          type?: string;
          /** @description Filter by exact status, e.g. 'Not Started', 'Ready To Donate', 'Donated'. */
          status?: string;
          /** @description Restrict to a single chapter id (must be within the user's access). */
          chapter?: number;
          /** @description Whether to include Donated devices. Defaults to true. */
          includeDonated?: boolean;
          /** @description Whether to include Scrapped devices. Defaults to true. */
          includeScrapped?: boolean;
          /** @description Restrict to devices donated by this party id. */
          donorId?: number;
          /** @description Restrict to devices received by this party id. */
          recipientId?: number;
          /** @description Sort column: id, type, manufacturer, model, year, cpu, operatingSystem, ram, storage, status, chapter or acquisitionDate. Defaults to id. */
          sort?: string;
          /** @description Sort direction: asc (default) or desc. */
          dir?: string;
        };
      };
      responses: {
        /** @description Devices retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["GetDeviceResponse"][];
          };
        };
        /** @description Missing/invalid pagination or filter parameters */
        400: {
          content: never;
        };
        /** @description Access denied for the requested chapter */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/desktop": {
    /**
     * Add a new desktop to the database
     * @description Adds a desktop with the specified attributes
     */
    post: {
      requestBody: {
        content: {
          /**
           * @example {
           *   "chapterId": 1,
           *   "manufacturer": "Dell",
           *   "model": "Optiplex 7010",
           *   "year": 2022,
           *   "status": "Not Started",
           *   "assetId": null,
           *   "cpu": null,
           *   "ram": null,
           *   "ramGeneration": null,
           *   "storageAmount": null,
           *   "storageType": null,
           *   "value": null,
           *   "acquisitionDate": null,
           *   "recipientId": null,
           *   "donorId": null,
           *   "hasWifi": null
           * }
           */
          "application/json": components["schemas"]["InsertDesktopRequest"];
        };
      };
      responses: {
        /** @description Desktop added successfully; returns the new asset id */
        201: {
          content: {
            "application/json": components["schemas"]["IdResponse"];
          };
        };
        /** @description Missing required parameters or invalid field values */
        400: {
          content: never;
        };
        /** @description Asset ID already exists */
        409: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/desktop/{id}": {
    /**
     * Updates a desktop in the database
     * @description Updates a desktop with the specified ID and attributes
     */
    put: {
      parameters: {
        path: {
          /** @description The asset ID of the desktop to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          /**
           * @example {
           *   "chapterId": 1,
           *   "manufacturer": "Dell",
           *   "model": "Optiplex 7010",
           *   "year": 2022,
           *   "status": "Not Started",
           *   "assetId": 10000,
           *   "cpu": null,
           *   "ram": null,
           *   "ramGeneration": null,
           *   "storageAmount": null,
           *   "storageType": null,
           *   "value": null,
           *   "acquisitionDate": null,
           *   "recipientId": null,
           *   "donorId": null,
           *   "hasWifi": null
           * }
           */
          "application/json": components["schemas"]["InsertDesktopRequest"];
        };
      };
      responses: {
        /** @description Desktop updated successfully */
        201: {
          content: never;
        };
        /** @description Missing required parameters or invalid field values */
        400: {
          content: never;
        };
        /** @description Desktop with specified ID does not exist */
        401: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/laptop": {
    /**
     * Add a new laptop to the database
     * @description Adds a laptop with the specified attributes
     */
    post: {
      requestBody: {
        content: {
          /**
           * @example {
           *   "chapterId": 1,
           *   "manufacturer": "Dell",
           *   "model": "Optiplex 7010",
           *   "year": 2022,
           *   "status": "Not Started",
           *   "includesCharger": "Included",
           *   "assetId": null,
           *   "cpu": null,
           *   "ram": null,
           *   "ramGeneration": null,
           *   "storageAmount": null,
           *   "storageType": null,
           *   "value": null,
           *   "acquisitionDate": null,
           *   "recipientId": null,
           *   "donorId": null,
           *   "designBatteryCapacity": null,
           *   "actualBatteryCapacity": null
           * }
           */
          "application/json": components["schemas"]["InsertLaptopRequest"];
        };
      };
      responses: {
        /** @description Laptop added successfully; returns the new asset id */
        201: {
          content: {
            "application/json": components["schemas"]["IdResponse"];
          };
        };
        /** @description Missing required parameters or invalid field values */
        400: {
          content: never;
        };
        /** @description Asset ID already exists */
        409: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/laptop/{id}": {
    /**
     * Updates a laptop in the database
     * @description Updates a laptop with the specified ID and attributes
     */
    put: {
      parameters: {
        path: {
          /** @description The asset ID of the laptop to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          /**
           * @example {
           *   "chapterId": 1,
           *   "manufacturer": "Dell",
           *   "model": "Optiplex 7010",
           *   "year": 2022,
           *   "status": "Not Started",
           *   "includesCharger": "Included",
           *   "assetId": 10000,
           *   "cpu": null,
           *   "ram": null,
           *   "ramGeneration": null,
           *   "storageAmount": null,
           *   "storageType": null,
           *   "value": null,
           *   "acquisitionDate": null,
           *   "recipientId": null,
           *   "donorId": null,
           *   "designBatteryCapacity": null,
           *   "actualBatteryCapacity": null
           * }
           */
          "application/json": components["schemas"]["InsertLaptopRequest"];
        };
      };
      responses: {
        /** @description Laptop updated successfully */
        201: {
          content: never;
        };
        /** @description Missing required parameters or invalid field values */
        400: {
          content: never;
        };
        /** @description Laptop with specified ID does not exist */
        401: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/stats/avg-time": {
    /**
     * Average time from acquisition to donation
     * @description Returns the average number of days between acquisition and donation for donated devices, optionally filtered to specific chapters.
     */
    get: {
      parameters: {
        query?: {
          /** @description Comma-separated chapter IDs. Defaults to all accessible chapters. */
          chapters?: string;
        };
      };
      responses: {
        /** @description Average time retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["AvgTimeInInventoryResponse"];
          };
        };
        /** @description Access denied for a requested chapter */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/stats/chapter-activity": {
    /**
     * Chapter activity summary
     * @description Returns counts of active chapters, chapters working on devices, and chapters with pickups ready, across all chapters visible to the caller.
     */
    get: {
      responses: {
        /** @description Chapter activity stats retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["ChapterActivityStatsResponse"];
          };
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/stats/chapter-inventory": {
    /**
     * Per-chapter inventory rollup
     * @description Returns device (by type and status), part and tool counts for each chapter the user can access.
     */
    get: {
      responses: {
        /** @description Chapter inventory summary retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["ChapterInventorySummary"][];
          };
        };
        /** @description Access denied for a requested chapter */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/stats/completion-rate": {
    /**
     * Donated vs total (non-scrapped) device completion rate
     * @description Returns the count of donated devices and the count of all non-scrapped/unknown devices, optionally filtered to specific chapters.
     */
    get: {
      parameters: {
        query?: {
          /** @description Comma-separated chapter IDs. Defaults to all accessible chapters. */
          chapters?: string;
        };
      };
      responses: {
        /** @description Completion rate data retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["CompletionRateResponse"];
          };
        };
        /** @description Access denied for a requested chapter */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/stats/count/{type}": {
    /**
     * Retrieve the number of devices of a given type
     * @description Returns the count of devices by type and status, optionally filtered to specific chapters. Status values: active (default), not-started, in-progress, ready-to-donate, donated. Type values: desktop, laptop, tablet, total.
     */
    get: {
      parameters: {
        query?: {
          /** @description Filter by status: active (default), not-started, in-progress, ready-to-donate, donated */
          status?: string;
          /** @description Comma-separated list of chapter IDs to filter by. Defaults to all accessible chapters. */
          chapters?: string;
        };
        path: {
          /** @description Device type: desktop, laptop, tablet, or total */
          type: string;
        };
      };
      responses: {
        /** @description Count retrieved successfully */
        200: {
          content: {
            "application/json": number;
          };
        };
        /** @description Invalid device type, status, or chapter ID */
        400: {
          content: never;
        };
        /** @description Access denied for a requested chapter */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/stats/counts": {
    /**
     * All dashboard counts in a single request
     * @description Returns all eight pipeline and device-type counts needed by the dashboard in one call, optionally filtered to specific chapters. Pipeline counts (not-started, in-progress, ready-to-donate, donated) cover all device types. Active type counts (desktop, laptop, tablet, total) exclude Donated and Ready To Donate devices.
     */
    get: {
      parameters: {
        query?: {
          /** @description Comma-separated list of chapter IDs to filter by. Defaults to all accessible chapters. */
          chapters?: string;
        };
      };
      responses: {
        /** @description Dashboard counts retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["DashboardCountsResponse"];
          };
        };
        /** @description Invalid chapter ID */
        400: {
          content: never;
        };
        /** @description Access denied for a requested chapter */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/stats/devices-donated": {
    /**
     * Monthly devices donated
     * @description Returns the count of devices donated per month for the last N months (default 12). Optionally filtered to specific chapters.
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of months to look back (1-120, default 12) */
          months?: string;
          /** @description Comma-separated chapter IDs. Defaults to all accessible chapters. */
          chapters?: string;
        };
      };
      responses: {
        /** @description Monthly donated data retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["MonthlyCountPoint"][];
          };
        };
        /** @description Invalid months value or chapter ID */
        400: {
          content: never;
        };
        /** @description Access denied for a requested chapter */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/stats/devices-received": {
    /**
     * Monthly devices received
     * @description Returns the count of devices received (by acquisition date) per month for the last N months (default 12). Optionally filtered to specific chapters.
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of months to look back (1-120, default 12) */
          months?: string;
          /** @description Comma-separated chapter IDs. Defaults to all accessible chapters. */
          chapters?: string;
        };
      };
      responses: {
        /** @description Monthly received data retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["MonthlyCountPoint"][];
          };
        };
        /** @description Invalid months value or chapter ID */
        400: {
          content: never;
        };
        /** @description Access denied for a requested chapter */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/stats/donated-value": {
    /**
     * Monthly value of donated devices
     * @description Returns the total value of donated devices per month for the last N months (default 12). Optionally filtered to specific chapters.
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of months to look back (1-120, default 12) */
          months?: string;
          /** @description Comma-separated chapter IDs. Defaults to all accessible chapters. */
          chapters?: string;
        };
      };
      responses: {
        /** @description Monthly value data retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["MonthlyValuePoint"][];
          };
        };
        /** @description Invalid months value or chapter ID */
        400: {
          content: never;
        };
        /** @description Access denied for a requested chapter */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/tablet": {
    /**
     * Add a new tablet to the database
     * @description Adds a tablet with the specified attributes
     */
    post: {
      requestBody: {
        content: {
          /**
           * @example {
           *   "chapterId": 1,
           *   "manufacturer": "Dell",
           *   "model": "Optiplex 7010",
           *   "year": 2022,
           *   "status": "Not Started",
           *   "includesCharger": "Included",
           *   "assetId": null,
           *   "cpu": null,
           *   "ram": null,
           *   "ramGeneration": null,
           *   "storageAmount": null,
           *   "storageType": null,
           *   "value": null,
           *   "acquisitionDate": null,
           *   "recipientId": null,
           *   "donorId": null,
           *   "workingBattery": "Yes"
           * }
           */
          "application/json": components["schemas"]["InsertTabletRequest"];
        };
      };
      responses: {
        /** @description Tablet added successfully; returns the new asset id */
        201: {
          content: {
            "application/json": components["schemas"]["IdResponse"];
          };
        };
        /** @description Missing required parameters or invalid field values */
        400: {
          content: never;
        };
        /** @description Asset ID already exists */
        409: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/tablet/{id}": {
    /**
     * Updates a tablet in the database
     * @description Updates a tablet with the specified ID and attributes
     */
    put: {
      parameters: {
        path: {
          /** @description The asset ID of the tablet to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          /**
           * @example {
           *   "chapterId": 1,
           *   "manufacturer": "Dell",
           *   "model": "Optiplex 7010",
           *   "year": 2022,
           *   "status": "Not Started",
           *   "includesCharger": "Included",
           *   "assetId": 10000,
           *   "cpu": null,
           *   "ram": null,
           *   "ramGeneration": null,
           *   "storageAmount": null,
           *   "storageType": null,
           *   "value": null,
           *   "acquisitionDate": null,
           *   "recipientId": null,
           *   "donorId": null,
           *   "workingBattery": "Yes"
           * }
           */
          "application/json": components["schemas"]["InsertTabletRequest"];
        };
      };
      responses: {
        /** @description Tablet updated successfully */
        201: {
          content: never;
        };
        /** @description Missing required parameters or invalid field values */
        400: {
          content: never;
        };
        /** @description Tablet with specified ID does not exist */
        401: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/{id}": {
    /**
     * Retrieve a device with a specific ID
     * @description Returns the device with the given ID.
     */
    get: {
      parameters: {
        path: {
          /** @description Device ID: A unique number assigned to each device */
          id: string;
        };
      };
      responses: {
        /** @description Device retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["GetDeviceResponse"];
          };
        };
        /** @description Non-numeric or non-positive device ID */
        400: {
          content: never;
        };
        /** @description ID does not match any existing devices */
        404: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/devices/{id}/changelog": {
    /** Get the service history for a device */
    get: {
      parameters: {
        path: {
          /** @description Device ID for which to retrieve changelog */
          id: string;
        };
      };
      responses: {
        /** @description Changelog fetched successfully */
        200: {
          content: {
            "application/json": components["schemas"]["DeviceChangelogResponse"][];
          };
        };
        /** @description Non-positive or non-numeric ID provided */
        400: {
          content: never;
        };
        /** @description Device not found */
        404: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/health": {
    /** Health check */
    get: {
      responses: {
        /** @description Service is up */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/lookup": {
    /**
     * Retrieve all lookup option lists
     * @description Returns all dropdown/combo option lists in a single request.
     */
    get: {
      responses: {
        /** @description Lookup data */
        200: {
          content: {
            "application/json": components["schemas"]["LookupResponse"];
          };
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/lookup/manufacturers": {
    /** Add a manufacturer */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddLookupRequest"];
        };
      };
      responses: {
        /** @description Added */
        201: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/lookup/manufacturers/{name}": {
    /** Delete a manufacturer */
    delete: {
      parameters: {
        path: {
          name: string;
        };
      };
      responses: {
        /** @description Deleted */
        204: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/lookup/operating-systems": {
    /** Add an operating system */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddLookupRequest"];
        };
      };
      responses: {
        /** @description Added */
        201: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/lookup/operating-systems/{name}": {
    /** Delete an operating system */
    delete: {
      parameters: {
        path: {
          name: string;
        };
      };
      responses: {
        /** @description Deleted */
        204: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/lookup/part-types": {
    /** Add a part type */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddLookupRequest"];
        };
      };
      responses: {
        /** @description Added */
        201: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/lookup/part-types/{name}": {
    /** Delete a part type */
    delete: {
      parameters: {
        path: {
          name: string;
        };
      };
      responses: {
        /** @description Deleted */
        204: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/lookup/ram-generations": {
    /** Add a RAM generation */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddLookupRequest"];
        };
      };
      responses: {
        /** @description Added */
        201: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/lookup/ram-generations/{name}": {
    /** Delete a RAM generation */
    delete: {
      parameters: {
        path: {
          name: string;
        };
      };
      responses: {
        /** @description Deleted */
        204: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/lookup/storage-types": {
    /** Add a storage type */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddLookupRequest"];
        };
      };
      responses: {
        /** @description Added */
        201: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/lookup/storage-types/{name}": {
    /** Delete a storage type */
    delete: {
      parameters: {
        path: {
          name: string;
        };
      };
      responses: {
        /** @description Deleted */
        204: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/parts": {
    /**
     * Get a page of parts currently in inventory
     * @description Returns a filtered, paginated page of parts the user can access, ordered by type then id. pageSize is required.
     */
    get: {
      parameters: {
        query: {
          /** @description Number of records per page (1-1000). Required. */
          pageSize: number;
          /** @description Zero-based page index. Defaults to 0. */
          pageKey?: number;
          /** @description Free-text search matched against every part field (id, type, description, etc.). */
          search?: string;
          /** @description Filter by part type. */
          type?: string;
          /** @description Filter by source: 'donated' or 'purchased'. */
          source?: string;
          /** @description Whether to include parts already contained in a device. Defaults to true. */
          includeInDevice?: boolean;
          /** @description Restrict to a single chapter id (must be within the user's access). */
          chapter?: number;
          /** @description Restrict to parts donated by this party id. */
          donorId?: number;
        };
      };
      responses: {
        /** @description Parts fetched successfully */
        200: {
          content: {
            "application/json": components["schemas"]["PartResponse"][];
          };
        };
        /** @description Missing/invalid pagination or filter parameters */
        400: {
          content: never;
        };
        /** @description Access denied for the requested chapter */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
    /**
     * Add a new part to the database
     * @description Adds a new part with the specified attributes
     */
    post: {
      requestBody: {
        content: {
          /**
           * @example {
           *     "chapterId": 1,
           *     "type": "SATA SSD",
           *     "description": "256 GB SSD",
           *     "wasPurchased": true,
           *     "containedIn": null,
           *     "id": null,
           *     "acquisitionDate": null,
           *     "value": 0.00,
           *     "donorId": null
           * }
           */
          "application/json": components["schemas"]["InsertPartRequest"];
        };
      };
      responses: {
        /** @description Part added successfully; returns the new asset id */
        201: {
          content: {
            "application/json": components["schemas"]["IdResponse"];
          };
        };
        /** @description Missing required parameters or invalid field values */
        400: {
          content: never;
        };
        /** @description Asset ID already exists */
        409: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/parts/device/{deviceId}": {
    /** Get all parts linked to a specific device */
    get: {
      parameters: {
        path: {
          /** @description Device ID whose linked parts to retrieve */
          deviceId: string;
        };
      };
      responses: {
        /** @description Parts fetched successfully */
        200: {
          content: {
            "application/json": components["schemas"]["PartResponse"][];
          };
        };
        /** @description Non-positive or non-numeric device ID */
        400: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/parts/type-counts": {
    /**
     * Get the total part count per type
     * @description Returns the number of parts of each type matching the given filters (unpaginated). Accepts the same filter parameters as the parts list, so the grouped UI can show accurate group totals while rows stream in.
     */
    get: {
      parameters: {
        query?: {
          /** @description Free-text search matched against every part field. */
          search?: string;
          /** @description Filter by part type. */
          type?: string;
          /** @description Filter by source: 'donated' or 'purchased'. */
          source?: string;
          /** @description Whether to include parts already contained in a device. Defaults to true. */
          includeInDevice?: boolean;
          /** @description Restrict to a single chapter id (must be within the user's access). */
          chapter?: number;
          /** @description Restrict to parts donated by this party id. */
          donorId?: number;
        };
      };
      responses: {
        /** @description Per-type counts fetched successfully */
        200: {
          content: {
            "application/json": components["schemas"]["PartTypeCountResponse"][];
          };
        };
        /** @description Invalid filter parameters */
        400: {
          content: never;
        };
        /** @description Access denied for the requested chapter */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/parts/{id}": {
    /** Get information regarding a part currently in inventory */
    get: {
      parameters: {
        path: {
          /** @description Part ID whose information to retrieve */
          id: string;
        };
      };
      responses: {
        /** @description Parts fetched successfully */
        200: {
          content: {
            "application/json": components["schemas"]["PartResponse"];
          };
        };
        /** @description Non-positive or non-numeric ID provided */
        400: {
          content: never;
        };
        /** @description No part with provided ID found */
        404: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
    /** Update a part currently in inventory */
    put: {
      parameters: {
        path: {
          /** @description Part ID to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          /**
           * @example {
           *     "chapterId": 1,
           *     "type": "SATA SSD",
           *     "description": "256 GB SSD",
           *     "wasPurchased": true,
           *     "containedIn": null,
           *     "id": null,
           *     "acquisitionDate": null,
           *     "value": 0.00,
           *     "donorId": null
           * }
           */
          "application/json": components["schemas"]["InsertPartRequest"];
        };
      };
      responses: {
        /** @description Part updated successfully */
        201: {
          content: {
            "application/json": components["schemas"]["PartResponse"];
          };
        };
        /** @description Missing required parameters or invalid parameter */
        400: {
          content: never;
        };
        /** @description Part with specified ID does not exist */
        401: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
    /** Delete a part currently in inventory */
    delete: {
      parameters: {
        path: {
          /** @description Part ID to delete */
          id: string;
        };
      };
      responses: {
        /** @description Part deleted */
        204: {
          content: {
            "application/json": components["schemas"]["PartResponse"];
          };
        };
        /** @description Non-positive or non-numeric ID provided */
        400: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/parts/{id}/changelog": {
    /** Get the service history for a part */
    get: {
      parameters: {
        path: {
          /** @description Part ID to retrieve changelog for */
          id: string;
        };
      };
      responses: {
        /** @description Changelog fetched successfully */
        200: {
          content: {
            "application/json": components["schemas"]["PartChangelogResponse"][];
          };
        };
        /** @description Non-positive or non-numeric ID provided */
        400: {
          content: never;
        };
        /** @description Part not found */
        404: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/party": {
    /**
     * Retrieve all parties
     * @description Returns a list of all parties.
     */
    get: {
      parameters: {
        query?: {
          type?: string;
        };
      };
      responses: {
        /** @description Parties retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["GetPartyResponse"][];
          };
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/party/organization": {
    /**
     * Insert a new organization
     * @description Creates a new organization with the provided attributes
     */
    post: {
      requestBody: {
        content: {
          /**
           * @example {
           *     "name": "Rose-Hulman Institute of Technology",
           *     "location": "(5500 Wabash Ave, Terre Haute, IN, 47803, USA)",
           *     "contactName": null,
           *     "contactEmail": null
           * }
           */
          "application/json": components["schemas"]["InsertOrganizationRequest"];
        };
      };
      responses: {
        /** @description Organization added successfully */
        201: {
          content: never;
        };
        /** @description Missing required parameters or invalid field values */
        400: {
          content: never;
        };
        /** @description Party ID already exists */
        409: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/party/organization/{id}": {
    /**
     * Update an existing organization
     * @description Updates the organization with the given ID
     */
    put: {
      parameters: {
        path: {
          /** @description Party ID of the organization to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          /**
           * @example {
           *     "name": "Rose-Hulman Institute of Technology",
           *     "location": "(5500 Wabash Ave, Terre Haute, IN, 47803, USA)",
           *     "contactName": "John Smith",
           *     "contactEmail": "jsmith@rose-hulman.edu"
           * }
           */
          "application/json": components["schemas"]["UpdateOrganizationRequest"];
        };
      };
      responses: {
        /** @description Organization updated successfully */
        204: {
          content: never;
        };
        /** @description Invalid ID or missing/invalid field values */
        400: {
          content: never;
        };
        /** @description No party with the given ID exists */
        404: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/party/person": {
    /**
     * Insert a new person
     * @description Creates a new person with the provided attributes
     */
    post: {
      requestBody: {
        content: {
          /**
           * @example {
           *     "name": "John Doe",
           *     "location": "(123 Main St, Terre Haute, IN, 47803, USA)",
           *     "email": ""
           * }
           */
          "application/json": components["schemas"]["InsertPersonRequest"];
        };
      };
      responses: {
        /** @description Person added successfully */
        201: {
          content: never;
        };
        /** @description Missing required parameters or invalid field values */
        400: {
          content: never;
        };
        /** @description Party ID already exists */
        409: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/party/person/{id}": {
    /**
     * Update an existing person
     * @description Updates the person with the given ID
     */
    put: {
      parameters: {
        path: {
          /** @description Party ID of the person to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          /**
           * @example {
           *     "name": "Jane Doe",
           *     "location": "(456 Elm St, Terre Haute, IN, 47803, USA)",
           *     "email": "jane@example.com"
           * }
           */
          "application/json": components["schemas"]["UpdatePersonRequest"];
        };
      };
      responses: {
        /** @description Person updated successfully */
        204: {
          content: never;
        };
        /** @description Invalid ID or missing/invalid field values */
        400: {
          content: never;
        };
        /** @description No party with the given ID exists */
        404: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/party/{id}": {
    /**
     * Retrieve a party with specific ID
     * @description Returns the device with the given ID.
     */
    get: {
      parameters: {
        path: {
          /** @description Party ID: A unique number assigned to each party */
          id: string;
        };
      };
      responses: {
        /** @description Party retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["GetPartyResponse"];
          };
        };
        /** @description Non-numeric or non-positive party ID */
        400: {
          content: never;
        };
        /** @description ID does not match any existing devices */
        404: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/ping": {
    /** Ping */
    get: {
      responses: {
        /** @description Returns pong */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/tools": {
    /**
     * Retrieve a page of tools
     * @description Returns a filtered, paginated page of tools the user can access, ordered by id. pageSize is required.
     */
    get: {
      parameters: {
        query: {
          /** @description Number of records per page (1-1000). Required. */
          pageSize: number;
          /** @description Zero-based page index. Defaults to 0. */
          pageKey?: number;
          /** @description Free-text search matched against every tool field (id, description, etc.). */
          search?: string;
          /** @description Restrict to a single chapter id (must be within the user's access). */
          chapter?: number;
          /** @description Restrict to tools donated by this party id. */
          donorId?: number;
        };
      };
      responses: {
        /** @description Tools received successfully */
        200: {
          content: {
            "application/json": components["schemas"]["GetToolResponse"][];
          };
        };
        /** @description Missing/invalid pagination or filter parameters */
        400: {
          content: never;
        };
        /** @description Access denied for the requested chapter */
        403: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
    /**
     * Add a new tool to the database
     * @description Adds a tool with the specified attributes
     */
    post: {
      requestBody: {
        content: {
          /**
           * @example {
           *   "chapterId": 1,
           *   "assetId": null,
           *   "description": null,
           *   "acquisitionDate": null,
           *   "value": null,
           *   "donorId": null
           * }
           */
          "application/json": components["schemas"]["InsertToolRequest"];
        };
      };
      responses: {
        /** @description Tool added successfully; returns the new asset id */
        201: {
          content: {
            "application/json": components["schemas"]["IdResponse"];
          };
        };
        /** @description Missing required parameters or invalid field values */
        400: {
          content: never;
        };
        /** @description Asset ID already exists */
        409: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/tools/{id}": {
    /**
     * Retrieve a specific tool
     * @description Returns a tool with specified ID
     */
    get: {
      parameters: {
        path: {
          /** @description Tool ID: A unique number assigned to each tool */
          id: string;
        };
      };
      responses: {
        /** @description Tool retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["GetToolResponse"];
          };
        };
        /** @description Non-numeric or non-positive tool ID */
        400: {
          content: never;
        };
        /** @description ID does not match any existing tools */
        404: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
    /**
     * Updates a tool in the database
     * @description Updates a tool with the specified ID and attributes
     */
    put: {
      parameters: {
        path: {
          /** @description The asset ID of the tool to update */
          id: string;
        };
      };
      requestBody: {
        content: {
          /**
           * @example {
           *   "chapterId": 1,
           *   "assetId": null,
           *   "description": null,
           *   "acquisitionDate": null,
           *   "value": null,
           *   "donorId": null
           * }
           */
          "application/json": components["schemas"]["InsertToolRequest"];
        };
      };
      responses: {
        /** @description Tool updated successfully */
        201: {
          content: never;
        };
        /** @description Missing required parameters or invalid field values */
        400: {
          content: never;
        };
        /** @description Tool with specified ID does not exist */
        401: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
    /** Delete a tool currently in inventory */
    delete: {
      parameters: {
        path: {
          /** @description Tool ID to delete */
          id: string;
        };
      };
      responses: {
        /** @description Tool deleted successfully */
        204: {
          content: {
            "application/json": components["schemas"]["GetToolResponse"];
          };
        };
        /** @description Non-positive or non-numeric ID provided */
        400: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
  "/api/tools/{id}/changelog": {
    /** Get the changelog for a tool */
    get: {
      parameters: {
        path: {
          /** @description Tool ID to retrieve changelog for */
          id: string;
        };
      };
      responses: {
        /** @description Changelog fetched successfully */
        200: {
          content: {
            "application/json": components["schemas"]["ToolChangelogResponse"][];
          };
        };
        /** @description Non-positive or non-numeric ID provided */
        400: {
          content: never;
        };
        /** @description Tool not found */
        404: {
          content: never;
        };
        /** @description Database error */
        500: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ChapterRole: {
      /** Format: int32 */
      chapterId: number;
      role?: string;
    };
    AddAffiliationRequest: {
      /** Format: int32 */
      chapterId: number;
      role?: string;
    };
    AddLookupRequest: {
      name?: string;
    };
    CreateAccountRequest: {
      name?: string;
      username?: string;
      password?: string;
      /** Format: int32 */
      chapterId: number;
      role?: string;
    };
    CreateChapterRequest: {
      name?: string;
    };
    InsertDesktopRequest: {
      /** Format: int32 */
      chapterId: number;
      manufacturer?: string;
      model?: string;
      /** Format: int32 */
      year: number;
      status?: string;
      /** Format: int32 */
      assetId?: number;
      cpu?: string;
      /** Format: int32 */
      ram?: number;
      ramGeneration?: string;
      /** Format: int32 */
      storageAmount?: number;
      storageType?: string;
      /** Format: double */
      value?: number;
      /** Format: date */
      acquisitionDate?: string;
      /** Format: int32 */
      recipientId?: number;
      /** Format: int32 */
      donorId?: number;
      hasWifi?: boolean;
      operatingSystem?: string;
    };
    InsertLaptopRequest: {
      /** Format: int32 */
      chapterId: number;
      manufacturer?: string;
      model?: string;
      /** Format: int32 */
      year: number;
      status?: string;
      includesCharger?: string;
      /** Format: int32 */
      assetId?: number;
      cpu?: string;
      /** Format: int32 */
      ram?: number;
      ramGeneration?: string;
      /** Format: int32 */
      storageAmount?: number;
      storageType?: string;
      /** Format: double */
      value?: number;
      /** Format: date */
      acquisitionDate?: string;
      /** Format: int32 */
      recipientId?: number;
      /** Format: int32 */
      donorId?: number;
      /** Format: int32 */
      designBatteryCapacity?: number;
      /** Format: int32 */
      actualBatteryCapacity?: number;
      operatingSystem?: string;
    };
    InsertOrganizationRequest: {
      name?: string;
      location?: string;
      contactName?: string;
      contactEmail?: string;
    };
    InsertPartRequest: {
      /** Format: int32 */
      chapterId: number;
      type?: string;
      description?: string;
      wasPurchased?: boolean;
      /** Format: int32 */
      containedIn?: number;
      /** Format: int32 */
      id?: number;
      /** Format: date */
      acquisitionDate?: string;
      /** Format: double */
      value?: number;
      /** Format: int32 */
      donorId?: number;
    };
    InsertPersonRequest: {
      name?: string;
      location?: string;
      email?: string;
    };
    InsertTabletRequest: {
      /** Format: int32 */
      chapterId: number;
      manufacturer?: string;
      model?: string;
      /** Format: int32 */
      year: number;
      status?: string;
      includesCharger?: string;
      /** Format: int32 */
      assetId?: number;
      cpu?: string;
      /** Format: int32 */
      ram?: number;
      ramGeneration?: string;
      /** Format: int32 */
      storageAmount?: number;
      storageType?: string;
      /** Format: double */
      value?: number;
      /** Format: date */
      acquisitionDate?: string;
      /** Format: int32 */
      recipientId?: number;
      /** Format: int32 */
      donorId?: number;
      workingBattery?: string;
      operatingSystem?: string;
    };
    InsertToolRequest: {
      /** Format: int32 */
      chapterId: number;
      /** Format: int32 */
      assetId?: number;
      description?: string;
      /** Format: date */
      acquisitionDate?: string;
      /** Format: double */
      value?: number;
      /** Format: int32 */
      donorId?: number;
    };
    LoginRequest: {
      username?: string;
      password?: string;
      salt?: string;
    };
    PostNoteRequest: {
      text?: string;
    };
    UpdateAffiliationRequest: {
      role?: string;
    };
    UpdateOrganizationRequest: {
      name?: string;
      location?: string;
      contactName?: string;
      contactEmail?: string;
    };
    UpdatePasswordRequest: {
      currentPassword?: string;
      newPassword?: string;
    };
    UpdatePersonRequest: {
      name?: string;
      location?: string;
      email?: string;
    };
    AccountSummary: {
      /** Format: int32 */
      id: number;
      username?: string;
      name?: string;
      chapterRoles?: components["schemas"]["ChapterRole"][];
    };
    AvgTimeInInventoryResponse: {
      /** Format: double */
      avgDays?: number;
      /** Format: int32 */
      sampleSize: number;
    };
    ChapterActivityStatsResponse: {
      /** Format: int32 */
      totalChapters: number;
      /** Format: int32 */
      activeChapters: number;
      /** Format: int32 */
      chaptersWithPickupsReady: number;
      /** Format: int32 */
      chaptersWorkingOnDevices: number;
    };
    ChapterInventorySummary: {
      /** Format: int32 */
      chapterId: number;
      chapterName?: string;
      /** Format: int32 */
      desktopCount: number;
      /** Format: int32 */
      laptopCount: number;
      /** Format: int32 */
      tabletCount: number;
      /** Format: int32 */
      notStarted: number;
      /** Format: int32 */
      inProgress: number;
      /** Format: int32 */
      readyToDonate: number;
      /** Format: int32 */
      donated: number;
      /** Format: int32 */
      scrapped: number;
      /** Format: int32 */
      totalDevices: number;
      /** Format: int32 */
      partsCount: number;
      /** Format: int32 */
      toolsCount: number;
    };
    ChapterSummary: {
      /** Format: int32 */
      id: number;
      name?: string;
    };
    CompletionRateResponse: {
      /** Format: int32 */
      donated: number;
      /** Format: int32 */
      total: number;
    };
    DashboardCountsResponse: {
      /** Format: int32 */
      notStarted: number;
      /** Format: int32 */
      inProgress: number;
      /** Format: int32 */
      readyToDonate: number;
      /** Format: int32 */
      donated: number;
      /** Format: int32 */
      desktopActive: number;
      /** Format: int32 */
      laptopActive: number;
      /** Format: int32 */
      tabletActive: number;
      /** Format: int32 */
      totalActive: number;
    };
    DeviceChangelogResponse: {
      deviceType?: string;
      /** Format: int32 */
      deviceID?: number;
      modifiedBy?: string;
      /** Format: date-time */
      modifiedAt?: string;
      changeType?: string;
      /** Format: date */
      oldAcquisitionDate?: string;
      /** Format: date */
      newAcquisitionDate?: string;
      /** Format: double */
      oldValue?: number;
      /** Format: double */
      newValue?: number;
      /** Format: int32 */
      oldChapterID?: number;
      /** Format: int32 */
      newChapterID?: number;
      /** Format: int32 */
      oldDonorID?: number;
      /** Format: int32 */
      newDonorID?: number;
      oldManufacturer?: string;
      newManufacturer?: string;
      oldModel?: string;
      newModel?: string;
      /** Format: int32 */
      oldYear?: number;
      /** Format: int32 */
      newYear?: number;
      oldCPU?: string;
      newCPU?: string;
      /** Format: int32 */
      oldRam?: number;
      /** Format: int32 */
      newRam?: number;
      oldRamGeneration?: string;
      newRamGeneration?: string;
      /** Format: int32 */
      oldStorageAmount?: number;
      /** Format: int32 */
      newStorageAmount?: number;
      oldStorageType?: string;
      newStorageType?: string;
      oldStatus?: string;
      newStatus?: string;
      oldHasWifi?: boolean;
      newHasWifi?: boolean;
      oldIncludesCharger?: string;
      newIncludesCharger?: string;
      /** Format: int32 */
      oldDesignCapacity?: number;
      /** Format: int32 */
      newDesignCapacity?: number;
      /** Format: int32 */
      oldActualCapacity?: number;
      /** Format: int32 */
      newActualCapacity?: number;
      /** Format: double */
      oldBatteryHealth?: number;
      /** Format: double */
      newBatteryHealth?: number;
      oldWorkingBattery?: string;
      newWorkingBattery?: string;
      /** Format: date */
      oldDonatedDate?: string;
      /** Format: date */
      newDonatedDate?: string;
      oldOperatingSystem?: string;
      newOperatingSystem?: string;
      /** Format: int32 */
      oldRecipientID?: number;
      /** Format: int32 */
      newRecipientID?: number;
    };
    GetDeviceResponse: {
      type?: string;
      /** Format: int32 */
      id: number;
      /** Format: date */
      acquisitionDate?: string;
      /** Format: double */
      value: number;
      manufacturer?: string;
      model?: string;
      /** Format: int32 */
      year: number;
      cpu?: string;
      /** Format: int32 */
      ram: number;
      ramGeneration?: string;
      /** Format: int32 */
      storage: number;
      storageType?: string;
      status?: string;
      hasWifi?: boolean;
      includesCharger?: string;
      /** Format: int32 */
      designBatteryCapacity?: number;
      /** Format: int32 */
      actualBatteryCapacity?: number;
      /** Format: double */
      batteryHealth?: number;
      workingBattery?: string;
      chapter?: string;
      /** Format: date */
      donatedDate?: string;
      operatingSystem?: string;
      /** Format: int32 */
      donorId?: number;
      /** Format: int32 */
      recipientId?: number;
    };
    GetPartyResponse: {
      /** Format: int32 */
      id: number;
      name?: string;
      location?: string;
      individualEmail?: string;
      contactName?: string;
      contactEmail?: string;
    };
    GetToolResponse: {
      /** Format: int32 */
      id: number;
      /** Format: date */
      acquisitionDate?: string;
      /** Format: double */
      value?: number;
      description?: string;
      /** Format: int32 */
      chapterId: number;
      /** Format: int32 */
      donorId?: number;
    };
    IdResponse: {
      /** Format: int32 */
      id: number;
    };
    LoginResponse: {
      token?: string;
      username?: string;
      chapterRoles?: components["schemas"]["ChapterRole"][];
      role?: string;
    };
    LookupResponse: {
      deviceStatuses?: string[];
      chargerStatuses?: string[];
      workingBatteryOpts?: string[];
      manufacturers?: string[];
      ramGenerations?: string[];
      storageTypes?: string[];
      partTypes?: string[];
      operatingSystems?: string[];
    };
    MonthlyCountPoint: {
      /** Format: int32 */
      year: number;
      /** Format: int32 */
      month: number;
      /** Format: int64 */
      count: number;
    };
    MonthlyValuePoint: {
      /** Format: int32 */
      year: number;
      /** Format: int32 */
      month: number;
      /** Format: double */
      value: number;
    };
    NoteResponse: {
      /** Format: int32 */
      id: number;
      text?: string;
      date?: string;
      /** Format: int32 */
      assetId: number;
    };
    PartChangelogResponse: {
      /** Format: int32 */
      partID?: number;
      modifiedBy?: string;
      /** Format: date-time */
      modifiedAt?: string;
      changeType?: string;
      /** Format: date */
      oldAcquisitionDate?: string;
      /** Format: date */
      newAcquisitionDate?: string;
      /** Format: double */
      oldValue?: number;
      /** Format: double */
      newValue?: number;
      /** Format: int32 */
      oldChapterID?: number;
      /** Format: int32 */
      newChapterID?: number;
      /** Format: int32 */
      oldDonorID?: number;
      /** Format: int32 */
      newDonorID?: number;
      oldType?: string;
      newType?: string;
      oldDescription?: string;
      newDescription?: string;
      oldWasPurchased?: boolean;
      newWasPurchased?: boolean;
      /** Format: int32 */
      oldContainedIn?: number;
      /** Format: int32 */
      newContainedIn?: number;
    };
    PartResponse: {
      /** Format: int32 */
      id: number;
      type?: string;
      description?: string;
      wasPurchased: boolean;
      /** Format: int32 */
      containedIn?: number;
      /** Format: int32 */
      chapterId: number;
      acquisitionDate?: string;
      /** Format: double */
      value?: number;
      /** Format: int32 */
      donorId?: number;
    };
    PartTypeCountResponse: {
      type?: string;
      /** Format: int32 */
      count: number;
    };
    ToolChangelogResponse: {
      /** Format: int32 */
      toolID?: number;
      modifiedBy?: string;
      /** Format: date-time */
      modifiedAt?: string;
      changeType?: string;
      /** Format: date */
      oldAcquisitionDate?: string;
      /** Format: date */
      newAcquisitionDate?: string;
      /** Format: double */
      oldValue?: number;
      /** Format: double */
      newValue?: number;
      /** Format: int32 */
      oldChapterID?: number;
      /** Format: int32 */
      newChapterID?: number;
      /** Format: int32 */
      oldDonorID?: number;
      /** Format: int32 */
      newDonorID?: number;
      oldDescription?: string;
      newDescription?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
