CREATE TABLE IF NOT EXISTS Tool (
    ID INTEGER NOT NULL PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES Asset(ID)
        ON UPDATE NO ACTION ON DELETE CASCADE,
    Description varchar(500) NOT NULL
);