CREATE TABLE IF NOT EXISTS Device (
    ID INTEGER PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES Asset(ID)
        ON UPDATE NO ACTION ON DELETE CASCADE,
    Manufacturer_ID INTEGER NOT NULL,
    FOREIGN KEY (Manufacturer_ID) REFERENCES Manufacturer(ID)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    Model VARCHAR(50) NOT NULL,
    Year INTEGER NULL,
    CHECK (Year >= 1980 AND Year <= EXTRACT(YEAR FROM CURRENT_DATE)),
    CPU VARCHAR(50) NULL,
    RAM INTEGER DEFAULT 0 NOT NULL,
    CHECK (RAM >= 0),
    RAM_Generation_ID INTEGER NULL,
    FOREIGN KEY (RAM_Generation_ID) REFERENCES Ram_Generation(ID)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    Storage_Amount INTEGER DEFAULT 0 NOT NULL,
    CHECK (Storage_Amount >= 0),
    Storage_Type_ID INTEGER NULL,
    FOREIGN KEY (Storage_Type_ID) REFERENCES Storage_Type(ID)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    Status Status NOT NULL,
    Recipient_ID INTEGER NULL,
    FOREIGN KEY (Recipient_ID) REFERENCES Party(ID)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    Donated_Date DATE NULL,
    OS_ID INTEGER NULL,
    FOREIGN KEY (OS_ID) REFERENCES Operating_System(ID)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);