CREATE TABLE IF NOT EXISTS Affiliated_With (
    Volunteer_ID INTEGER NOT NULL,
    FOREIGN KEY (Volunteer_ID) REFERENCES Volunteer(ID)
        ON UPDATE NO ACTION ON DELETE CASCADE,
    Chapter_ID INTEGER NOT NULL,
    FOREIGN KEY (Chapter_ID) REFERENCES Chapter(ID)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    Role_ID INTEGER NOT NULL,
    FOREIGN KEY (Role_ID) REFERENCES Role(ID)
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    PRIMARY KEY (Volunteer_ID, Chapter_ID)
);