CREATE TABLE IF NOT EXISTS Note (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Text VARCHAR(500) NULL,
    Date DATE NOT NULL,
    Asset_ID INTEGER NOT NULL,
    FOREIGN KEY (Asset_ID) REFERENCES Asset(ID)
        ON UPDATE NO ACTION ON DELETE CASCADE
);