create table Asset (
ID integer generated by default as identity (start with 1000) primary key,
Acquisition_Date date NOT NULL,
Value money NOT NULL,
Chapter_ID integer NOT NULL,
Donor_ID integer NULL,
foreign key (Chapter_ID) references Chapter(ID),
foreign key (Donor_ID) references Party(ID)
);