#!/usr/bin/env python3
"""Generate fake inventory workbooks for the development environment.

Produces one .xlsx workbook per chapter, each containing the seven sheets the
importer expects (``Desktops``, ``Laptops``, ``Tablets``, ``Ready To Donate``,
``Donated``, ``Parts``, ``Tools``). Column order in every sheet matches the
record-component order the importer reads (see ``importer/src/main/java/...``),
and the first two rows of each sheet are headers (the importer skips them).

The importer imports a whole workbook into a single chapter, so each generated
file targets one chapter. Import them with, e.g.:

    ./scripts/import-data.sh dev <tag> fake-purdue.xlsx "Purdue University"

Device IDs (Desktops/Laptops/Tablets/Ready To Donate) are explicit and must be
globally unique because Asset.ID is a primary key, so a single counter is shared
across every file and device type. Donated devices, parts, and tools get their
IDs auto-generated by the database.

Usage:
    python3 importer/generate_fake_data.py [output_dir]

Requires openpyxl (``pip install openpyxl``). ``output_dir`` defaults to
``importer/data``.
"""

from __future__ import annotations

import datetime as dt
import os
import random
import sys

from openpyxl import Workbook

# Deterministic output so regenerating produces the same data.
RANDOM_SEED = 20260722
# Explicit device IDs start well above the Asset identity sequence (START WITH
# 1000) so they never collide with auto-generated IDs (donated/parts/tools).
ID_START = 1_000_000

# (output filename, chapter name) — one workbook per chapter. These are all
# fake chapters; the real Rose-Hulman data lives in OldInventorySystem.xlsx, so
# none of these reuse that chapter name.
CHAPTERS = [
    ("fake-purdue.xlsx", "Purdue University"),
    ("fake-indiana.xlsx", "Indiana University Bloomington"),
    ("fake-illinois.xlsx", "University of Illinois Urbana-Champaign"),
    ("fake-georgia-tech.xlsx", "Georgia Institute of Technology"),
    ("fake-michigan.xlsx", "University of Michigan"),
    ("fake-ohio-state.xlsx", "Ohio State University"),
]

# Per-chapter counts. Explicit-ID devices (desktops + laptops + tablets +
# ready-to-donate) already exceed 1000; donated + parts + tools add more.
COUNTS = {
    "desktops": 220,
    "laptops": 320,
    "tablets": 180,
    "ready_to_donate": 160,
    "donated": 170,
    "parts_rows": 90,
    "tools_rows": 45,
}

PC_MANUFACTURERS = [
    "Dell", "HP", "Lenovo", "Apple", "ASUS", "Acer", "Microsoft", "MSI",
    "Toshiba", "Samsung",
]
TABLET_MANUFACTURERS = ["Apple", "Samsung", "Microsoft", "Lenovo", "Amazon", "Google"]

DESKTOP_MODELS = [
    "OptiPlex 7090", "ProDesk 600 G6", "ThinkCentre M720", "iMac 27\"",
    "ROG Strix GT15", "Aspire TC-895", "Vostro 3690", "EliteDesk 800 G5",
    "IdeaCentre 5", "Mac mini M1",
]
LAPTOP_MODELS = [
    "Latitude 5420", "EliteBook 840 G7", "ThinkPad T14", "MacBook Air",
    "ZenBook 14", "Aspire 5", "Surface Laptop 4", "Prestige 15",
    "Inspiron 15 3000", "Pavilion x360",
]
TABLET_MODELS = [
    "iPad Air", "Galaxy Tab S7", "Surface Go 3", "Tab M10", "Fire HD 10",
    "Pixel Tablet", "iPad Pro 11\"", "Galaxy Tab A8",
]

CPUS = [
    "Intel Core i3-10100", "Intel Core i5-8500", "Intel Core i5-1135G7",
    "Intel Core i7-9700", "Intel Core i7-1165G7", "Intel Xeon E5-2670",
    "AMD Ryzen 5 3600", "AMD Ryzen 7 5800X", "Apple M1", "Apple M2",
]
RAM_AMOUNTS = [4, 8, 16, 32]
RAM_GENERATIONS = ["DDR3", "DDR4", "DDR5", "LPDDR4"]
STORAGE_CAPACITIES = [128, 256, 512, 1024]
STORAGE_TYPES = ["SSD", "HDD", "NVMe SSD", "eMMC"]

PC_OS = ["Windows 11", "macOS", "Chrome OS", "ArchLinux", "Vanilla OS", "Unknown"]
TABLET_OS = ["iPad OS", "Android", "Chrome OS", "Windows 11", "iOS", "Unknown"]

DEVICE_STATUSES = ["Not Started", "In Progress", "Scrapped", "Unknown"]
CHARGER_STATUSES = ["Included", "Not Included", "Unknown"]
BATTERY_STATUSES = ["Yes", "No", "Unknown"]
DEVICE_TYPES = ["Desktop", "Laptop", "Tablet"]

NOTES_POOL = [
    "", "", "", "Needs cleaning.", "Missing screws on back panel.",
    "Wiped and reimaged.", "Minor cosmetic scratches.", "Battery health good.",
    "Donated by local business.", "Awaiting parts.", "Passed diagnostics.",
    "Keyboard replaced.", "Fan is a bit loud.",
]

RECIPIENT_ORGS = [
    "Boys & Girls Club", "Community Public Library", "Riverside Elementary",
    "Hope Shelter", "Senior Center", "Local Food Bank", "YMCA Chapter",
    "Habitat for Humanity", "Veterans Support Group", "Refugee Aid Center",
]
RECIPIENT_PEOPLE = [
    "Alex Johnson", "Maria Garcia", "James Smith", "Priya Patel",
    "Chen Wei", "Fatima Al-Sayed", "David Kim", "Sarah Williams",
    "Miguel Torres", "Emma Brown",
]

PART_TYPES = [
    "RAM", "Hard Drive", "SSD", "Power Supply", "Motherboard", "GPU", "CPU",
    "Charger", "Cable", "Screen", "Keyboard", "Battery",
]
PART_DESCRIPTIONS = [
    "8GB DDR4 SODIMM", "500GB 2.5\" SATA", "256GB NVMe M.2", "650W 80+ Bronze",
    "microATX board", "GTX 1060 6GB", "i5-8400 tray", "65W USB-C adapter",
    "3ft HDMI cable", "15.6\" FHD panel", "US layout membrane", "50Wh replacement",
]
TOOL_DESCRIPTIONS = [
    "Phillips #2 screwdriver", "Anti-static wrist strap", "Spudger set",
    "Precision bit kit", "Thermal paste tube", "Cable ties (100pk)",
    "Multimeter", "Compressed air can", "Tweezers", "Heat gun",
    "Label printer", "Isopropyl alcohol (500ml)",
]

DESKTOP_HEADERS = [
    "name", "ID", "manufacturer", "yearReleased", "notes", "currentStatus",
    "dateUpdated",
]
LAPTOP_HEADERS = [
    "name", "ID", "manufacturer", "yearReleased", "notes", "hasCharger",
    "hasWorkingBattery", "currentStatus", "dateUpdated",
]
TABLET_HEADERS = [
    "name", "ID", "manufacturer", "yearReleased", "notes", "chargerIncluded",
    "workingBattery", "currentStatus", "dateUpdated",
]
READY_HEADERS = [
    "deviceName", "manufacturer", "typeOfDevice", "estimatedYear", "cpu", "os",
    "ramAmount", "ramGeneration", "storageCapacity", "storageType",
    "estimatedValue", "notes", "ID",
]
DONATED_HEADERS = [
    "deviceName", "manufacturer", "typeOfDevice", "estimatedYear", "cpu", "os",
    "ramAmount", "ramGeneration", "storageCapacity", "storageType",
    "estimatedValue", "notes", "dateDonated", "recipient", "isOrganization",
]
PART_HEADERS = ["type", "description", "quantity", "wasDonated", "value"]
TOOL_HEADERS = ["description", "quantity", "value"]

TODAY = dt.date(2026, 7, 22)


def random_date(days_back: int) -> dt.date:
    return TODAY - dt.timedelta(days=random.randint(0, days_back))


def _write_sheet(wb: Workbook, title: str, headers: list[str], rows: list[list]):
    ws = wb.create_sheet(title=title)
    # Two header rows — the importer skips rows 0 and 1 and reads from row 2.
    ws.append([title] + [""] * (len(headers) - 1))
    ws.append(headers)
    for row in rows:
        ws.append(row)
    # Ensure date columns render as dates so Apache POI reads them as dates.
    for row_cells in ws.iter_rows(min_row=3):
        for cell in row_cells:
            if isinstance(cell.value, dt.date):
                cell.number_format = "yyyy-mm-dd"


def _make_workbook(id_counter: list[int]) -> Workbook:
    wb = Workbook()
    # Remove the default sheet created by openpyxl.
    wb.remove(wb.active)

    def next_id() -> int:
        v = id_counter[0]
        id_counter[0] += 1
        return v

    # Desktops
    desktops = []
    for _ in range(COUNTS["desktops"]):
        mfr = random.choice(PC_MANUFACTURERS)
        model = random.choice(DESKTOP_MODELS)
        desktops.append([
            f"{mfr} {model}",
            next_id(),
            mfr,
            random.randint(2012, 2024),
            random.choice(NOTES_POOL),
            random.choice(DEVICE_STATUSES),
            random_date(730),
        ])
    _write_sheet(wb, "Desktops", DESKTOP_HEADERS, desktops)

    # Laptops
    laptops = []
    for _ in range(COUNTS["laptops"]):
        mfr = random.choice(PC_MANUFACTURERS)
        model = random.choice(LAPTOP_MODELS)
        laptops.append([
            f"{mfr} {model}",
            next_id(),
            mfr,
            random.randint(2012, 2024),
            random.choice(NOTES_POOL),
            random.choice(CHARGER_STATUSES),
            random.choice(BATTERY_STATUSES),
            random.choice(DEVICE_STATUSES),
            random_date(730),
        ])
    _write_sheet(wb, "Laptops", LAPTOP_HEADERS, laptops)

    # Tablets
    tablets = []
    for _ in range(COUNTS["tablets"]):
        mfr = random.choice(TABLET_MANUFACTURERS)
        model = random.choice(TABLET_MODELS)
        tablets.append([
            f"{mfr} {model}",
            next_id(),
            mfr,
            random.randint(2013, 2024),
            random.choice(NOTES_POOL),
            random.choice(CHARGER_STATUSES),
            random.choice(BATTERY_STATUSES),
            random.choice(DEVICE_STATUSES),
            random_date(730),
        ])
    _write_sheet(wb, "Tablets", TABLET_HEADERS, tablets)

    # Ready To Donate
    ready = []
    for _ in range(COUNTS["ready_to_donate"]):
        dtype = random.choice(DEVICE_TYPES)
        if dtype == "Tablet":
            mfr = random.choice(TABLET_MANUFACTURERS)
            model = random.choice(TABLET_MODELS)
            os_val = random.choice(TABLET_OS)
        else:
            mfr = random.choice(PC_MANUFACTURERS)
            model = random.choice(DESKTOP_MODELS if dtype == "Desktop" else LAPTOP_MODELS)
            os_val = random.choice(PC_OS)
        ready.append([
            f"{mfr} {model}",
            mfr,
            dtype,
            random.randint(2014, 2024),
            random.choice(CPUS),
            os_val,
            random.choice(RAM_AMOUNTS),
            random.choice(RAM_GENERATIONS),
            random.choice(STORAGE_CAPACITIES),
            random.choice(STORAGE_TYPES),
            random.randint(40, 450),
            random.choice(NOTES_POOL),
            next_id(),
        ])
    _write_sheet(wb, "Ready To Donate", READY_HEADERS, ready)

    # Donated (IDs auto-generated by the DB)
    donated = []
    for _ in range(COUNTS["donated"]):
        dtype = random.choice(DEVICE_TYPES)
        if dtype == "Tablet":
            mfr = random.choice(TABLET_MANUFACTURERS)
            model = random.choice(TABLET_MODELS)
            os_val = random.choice(TABLET_OS)
        else:
            mfr = random.choice(PC_MANUFACTURERS)
            model = random.choice(DESKTOP_MODELS if dtype == "Desktop" else LAPTOP_MODELS)
            os_val = random.choice(PC_OS)
        is_org = random.random() < 0.6
        recipient = random.choice(RECIPIENT_ORGS if is_org else RECIPIENT_PEOPLE)
        donated.append([
            f"{mfr} {model}",
            mfr,
            dtype,
            random.randint(2014, 2024),
            random.choice(CPUS),
            os_val,
            random.choice(RAM_AMOUNTS),
            random.choice(RAM_GENERATIONS),
            random.choice(STORAGE_CAPACITIES),
            random.choice(STORAGE_TYPES),
            random.randint(40, 450),
            random.choice(NOTES_POOL),
            random_date(365),
            recipient,
            "Y" if is_org else "N",
        ])
    _write_sheet(wb, "Donated", DONATED_HEADERS, donated)

    # Parts (quantity expands into individual parts on import)
    parts = []
    for _ in range(COUNTS["parts_rows"]):
        parts.append([
            random.choice(PART_TYPES),
            random.choice(PART_DESCRIPTIONS),
            random.randint(1, 8),
            random.choice(["Y", "N"]),
            round(random.uniform(2.0, 120.0), 2),
        ])
    _write_sheet(wb, "Parts", PART_HEADERS, parts)

    # Tools (quantity expands into individual tools on import)
    tools = []
    for _ in range(COUNTS["tools_rows"]):
        tools.append([
            random.choice(TOOL_DESCRIPTIONS),
            random.randint(1, 5),
            round(random.uniform(3.0, 200.0), 2),
        ])
    _write_sheet(wb, "Tools", TOOL_HEADERS, tools)

    return wb


def main() -> None:
    out_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "data"
    )
    os.makedirs(out_dir, exist_ok=True)
    random.seed(RANDOM_SEED)

    # Shared, ever-increasing device-ID counter across all workbooks.
    id_counter = [ID_START]

    for filename, chapter_name in CHAPTERS:
        wb = _make_workbook(id_counter)
        path = os.path.join(out_dir, filename)
        wb.save(path)
        print(f"Wrote {path}  ->  chapter \"{chapter_name}\"")

    print(f"\nHighest device ID used: {id_counter[0] - 1}")
    print("Import each file with its chapter name, e.g.:")
    for filename, chapter_name in CHAPTERS:
        print(f'  ./scripts/import-data.sh dev <tag> {filename} "{chapter_name}"')


if __name__ == "__main__":
    main()
