-- ============================================================
-- CreateDatabase.sql
-- Combined PostgreSQL database creation script.
-- Order: types/enums -> base tables -> dependent tables
-- ============================================================


-- ------------------------------------------------------------
-- DOMAINS & COMPOSITE TYPES
-- ------------------------------------------------------------

create domain name_type as varchar(50);

create domain email_type as varchar(100);

create type address as (
    street   VARCHAR(100),
    city     VARCHAR(50),
    state    VARCHAR(50),
    zip_code VARCHAR(20),
    country  VARCHAR(50)
);

create type Manufacturer
as enum ('Dell', 'HP', 'Lenovo', 'Apple', 'Asus', 'Acer', 'Microsoft');

create type part_type
as enum ('SODIMM', 'DIMM', 'M.2 SSD', 'SATA SSD', 'HDD', 'CPU', 'GPU', 'Other');

create type Role
as enum ('President', 'Vice President', 'Secretary', 'Treasurer',
         'Director of Internal Affairs', 'Director of Membership',
         'Member', 'Guest');

create type Status
as enum ('Not Started', 'In Progress', 'Ready to Donate', 'Donated');

create type StorageType
as enum ('SSD', 'HDD');

create type ram_generation
as enum ('DDR2', 'DDR3', 'DDR4', 'DDR5');


-- ------------------------------------------------------------
-- BASE TABLES (no foreign-key dependencies on other tables)
-- ------------------------------------------------------------

create table Party (
    ID       integer generated always as identity primary key,
    Name     name_type NOT NULL,
    location address
);

create table Chapter (
    ID   integer generated always as identity primary key,
    Name name_type NOT NULL
);

create table Volunteer (
    ID       integer generated always as identity primary key,
    Name     name_type NOT NULL,
    Username name_type UNIQUE NOT NULL
);


-- ------------------------------------------------------------
-- PARTY SUB-TYPES  (depend on Party)
-- ------------------------------------------------------------

create table Person (
    ID    integer primary key,
    Email email_type NULL,
    foreign key (ID) references Party(ID)
);

create table Organization (
    ID           Integer primary key,
    ContactName  name_type  NULL,
    ContactEmail email_type NULL,
    foreign key (ID) references Party(ID)
);


-- ------------------------------------------------------------
-- ASSET  (depends on Chapter, Party)
-- ------------------------------------------------------------

create table Asset (
    ID               integer generated by default as identity (start with 1000) primary key,
    Acquisition_Date date    NOT NULL,
    Value            money   NOT NULL,
    Chapter_ID       integer NOT NULL,
    Donor_ID         integer NULL,
    foreign key (Chapter_ID) references Chapter(ID),
    foreign key (Donor_ID)   references Party(ID)
);


-- ------------------------------------------------------------
-- ASSET SUB-TYPES  (depend on Asset)
-- ------------------------------------------------------------

create table Device (
    ID             integer     primary key,
    Manufacturer   Manufacturer NOT NULL,
    Model          varchar(30)  NOT NULL,
    Year           integer      NOT NULL,
    CHECK (Year >= 1980 AND Year <= EXTRACT(YEAR FROM CURRENT_DATE)),
    CPU            varchar(30)  NULL,
    RAM            integer      DEFAULT 0 NOT NULL,
    CHECK (RAM >= 0),
    RAM_Generation ram_generation NULL,
    Storage_Amount integer      DEFAULT 0 NOT NULL,
    CHECK (Storage_Amount >= 0),
    Storage_Type   StorageType  NULL,
    Status         Status       NOT NULL,
    CHECK (Value >= 0),
    Recipient_ID   Integer      NULL,
    foreign key (ID)           references Asset(ID),
    foreign key (Recipient_ID) references Party(ID),
);

create table Part (
    ID            integer      primary key,
    Type          part_type    NOT NULL,
    Description   varchar(500) NOT NULL,
    Was_Purchased boolean      NOT NULL,
    Contained_In  integer      NULL,
    foreign key (ID)           references Asset(ID),
    foreign key (Contained_In) references Device(ID)
);

create table Tool (
    ID   integer     NOT NULL primary key,
    Type varchar(20) NOT NULL,
    foreign key (ID) references Asset(ID)
);

create table Note (
    ID       integer generated always as identity primary key,
    Text     varchar(500)             NOT NULL,
    Date     timestamp with time zone NOT NULL,
    Asset_ID integer                  NOT NULL,
    foreign key (Asset_ID) references Asset(ID)
);


-- ------------------------------------------------------------
-- DEVICE SUB-TYPES  (depend on Device)
-- ------------------------------------------------------------

create table Desktop (
    ID      integer primary key,
    HasWifi boolean NULL,
    foreign key (ID) references Device(ID)
);

create table Laptop (
    ID                      integer primary key,
    Design_battery_capacity Integer NOT NULL,
    check (Design_battery_capacity > 0),
    Actual_battery_capacity Integer NOT NULL,
    check (Actual_battery_capacity > 0),
    check (Actual_battery_capacity <= Design_battery_capacity),
    Battery_health NUMERIC GENERATED ALWAYS AS
        (Actual_battery_capacity::NUMERIC / Design_battery_capacity) STORED,
    Includes_charger boolean NOT NULL,
    foreign key (ID) references Device(ID)
);

create table Tablet (
    ID               integer primary key,
    Includes_charger boolean NOT NULL,
    Has_Cellular     boolean NOT NULL,
    foreign key (ID) references Device(ID)
);


-- ------------------------------------------------------------
-- AFFILIATED TABLES  (depend on Volunteer, Chapter)
-- ------------------------------------------------------------

create table Affiliated_With (
    Volunteer_ID integer NOT NULL,
    Chapter_ID   integer NOT NULL,
    role         Role    NOT NULL,
    PRIMARY KEY (Volunteer_ID, Chapter_ID),
    foreign key (Volunteer_ID) references Volunteer(ID),
    foreign key (Chapter_ID)   references Chapter(ID)
);
