CREATE USER importer WITH PASSWORD 'changeme_importer';

GRANT CONNECT ON DATABASE inventory TO importer;

GRANT USAGE ON SCHEMA public TO importer;

GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA public TO importer;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT, SELECT ON TABLES TO importer;